[
  {
    "id": "P-0001",
    "name": "Ahmed Youssef",
    "sex": "Male",
    "age": 54,
    "department": "Cardiology",
    "admissionDate": "2026-03-01",
    "bedNo": "C-12",
    "bloodType": "A+",
    "allergiesText": "Penicillin (rash), Peanuts (anaphylaxis)",
    "previousSurgeries": "CABG x3 (2018)",
    "admissionWeight": "88 kg",
    "todayWeight": "87.2 kg",
    "height": "176 cm",
    "bmi": "28.1",
    "admissionReason": "Chest pain on exertion, shortness of breath",
    "medicalDiagnosis": "Ischemic heart disease, stable angina",
    "complications": "None documented",
    "conditions": [
      "Hypertension",
      "Hyperlipidemia",
      "Ischemic heart disease"
    ],
    "medications": [
      "Aspirin 81 mg OD",
      "Atorvastatin 40 mg HS",
      "Bisoprolol 5 mg OD",
      "Isosorbide dinitrate 20 mg TID"
    ],
    "allergies": [
      "Penicillin",
      "Peanuts"
    ],
    "respType": "Spontaneous",
    "respRhythm": "Regular",
    "respRate": 18,
    "respPattern": "Eupnea",
    "chestExcursion": "Symmetrical",
    "o2Percent": 28,
    "o2Flow": 2,
    "o2Device": "Nasal cannula",
    "bronchialHygiene": "Cough and deep breathing q2h",
    "o2Sat": 96,
    "abg": "PaO2 82 mmHg / pH 7.40 / PaCO2 38 mmHg / HCO3 24",
    "incentiveSpirometer": "Used q4h",
    "mdiInhaler": "None",
    "breathSounds": "Clear bilaterally",
    "cough": "Occasional dry cough",
    "chestTube": "None",
    "pulseSeries": [78, 82, 80],
    "pulseRate": 80,
    "pulseRhythm": "Regular",
    "pulseAmplitude": "+2 normal",
    "heartSounds": "S1 S2 normal, no murmur",
    "bpSeries": "130/80, 128/78, 126/76",
    "map": "95 mmHg"
  },
  {
    "id": "P-0002",
    "name": "Mona Ibrahim",
    "sex": "Female",
    "age": 67,
    "department": "Respiratory",
    "admissionDate": "2026-02-26",
    "bedNo": "R-05",
    "bloodType": "O-",
    "allergiesText": "No known drug allergies",
    "previousSurgeries": "Cholecystectomy (2010)",
    "admissionWeight": "72 kg",
    "todayWeight": "71.4 kg",
    "height": "160 cm",
    "bmi": "27.9",
    "admissionReason": "Increasing shortness of breath and wheeze",
    "medicalDiagnosis": "COPD exacerbation",
    "complications": "Mild respiratory acidosis on admission",
    "conditions": [
      "COPD",
      "Former smoker"
    ],
    "medications": [
      "Tiotropium inhaler OD",
      "Salbutamol inhaler PRN",
      "Prednisolone 30 mg OD"
    ],
    "allergies": [],
    "respType": "Spontaneous",
    "respRhythm": "Regular",
    "respRate": 24,
    "respPattern": "Tachypnea",
    "chestExcursion": "Decreased bilaterally",
    "o2Percent": 32,
    "o2Flow": 3,
    "o2Device": "Venturi mask",
    "bronchialHygiene": "Chest physiotherapy + assisted coughing",
    "o2Sat": 92,
    "abg": "PaO2 60 mmHg / pH 7.33 / PaCO2 55 mmHg / HCO3 28",
    "incentiveSpirometer": "Not tolerated",
    "mdiInhaler": "Salbutamol 2 puffs q6h PRN",
    "breathSounds": "Diminished with bilateral wheezes",
    "cough": "Productive, small amount yellow sputum",
    "chestTube": "None",
    "pulseSeries": [96, 94, 98],
    "pulseRate": 96,
    "pulseRhythm": "Regular",
    "pulseAmplitude": "+1 weak",
    "heartSounds": "Normal, no added sounds",
    "bpSeries": "138/84, 136/82",
    "map": "100 mmHg"
  },
  {
    "id": "P-0003",
    "name": "Youssef Adel",
    "sex": "Male",
    "age": 32,
    "department": "General Surgery",
    "admissionDate": "2026-03-03",
    "bedNo": "S-09",
    "bloodType": "B+",
    "allergiesText": "Latex (contact dermatitis)",
    "previousSurgeries": "Appendectomy (childhood)",
    "admissionWeight": "80 kg",
    "todayWeight": "79.2 kg",
    "height": "178 cm",
    "bmi": "25.0",
    "admissionReason": "Right lower quadrant pain, suspected appendicitis",
    "medicalDiagnosis": "Acute appendicitis post‑laparoscopic appendectomy",
    "complications": "None",
    "conditions": [
      "Otherwise healthy"
    ],
    "medications": [
      "Ceftriaxone 1 g IV q24h",
      "Paracetamol 1 g IV q8h",
      "Enoxaparin 40 mg SC OD"
    ],
    "allergies": [
      "Latex"
    ],
    "respType": "Spontaneous",
    "respRhythm": "Regular",
    "respRate": 16,
    "respPattern": "Eupnea",
    "chestExcursion": "Symmetrical",
    "o2Percent": 21,
    "o2Flow": 0,
    "o2Device": "Room air",
    "bronchialHygiene": "Deep breathing and coughing q2h post‑op",
    "o2Sat": 98,
    "abg": "Not indicated",
    "incentiveSpirometer": "Used q2h",
    "mdiInhaler": "None",
    "breathSounds": "Clear",
    "cough": "Effective, non‑productive",
    "chestTube": "None",
    "pulseSeries": [76, 72, 74],
    "pulseRate": 74,
    "pulseRhythm": "Regular",
    "pulseAmplitude": "+2 normal",
    "heartSounds": "Normal",
    "bpSeries": "118/72, 120/74",
    "map": "88 mmHg"
  },
  {
    "id": "P-0004",
    "name": "Sara Mahmoud",
    "sex": "Female",
    "age": 45,
    "department": "Endocrinology",
    "admissionDate": "2026-02-20",
    "bedNo": "E-03",
    "bloodType": "AB+",
    "allergiesText": "Ibuprofen (GI upset)",
    "previousSurgeries": "C‑section (x2)",
    "admissionWeight": "95 kg",
    "todayWeight": "94.5 kg",
    "height": "162 cm",
    "bmi": "36.0",
    "admissionReason": "Poor glycemic control, polyuria, polydipsia",
    "medicalDiagnosis": "Type 2 diabetes mellitus, obesity, hypertension",
    "complications": "Peripheral neuropathy, microalbuminuria",
    "conditions": [
      "Type 2 diabetes mellitus",
      "Hypertension",
      "Obesity"
    ],
    "medications": [
      "Metformin 1 g BID",
      "Insulin glargine 24 units HS",
      "Losartan 50 mg OD"
    ],
    "allergies": [
      "Ibuprofen"
    ],
    "respType": "Spontaneous",
    "respRhythm": "Regular",
    "respRate": 18,
    "respPattern": "Eupnea",
    "chestExcursion": "Symmetrical",
    "o2Percent": 21,
    "o2Flow": 0,
    "o2Device": "Room air",
    "bronchialHygiene": "Independent coughing and deep breathing",
    "o2Sat": 97,
    "abg": "Not done",
    "incentiveSpirometer": "Not required",
    "mdiInhaler": "None",
    "breathSounds": "Clear",
    "cough": "None",
    "chestTube": "None",
    "pulseSeries": [84, 82, 86],
    "pulseRate": 84,
    "pulseRhythm": "Regular",
    "pulseAmplitude": "+2 normal",
    "heartSounds": "Normal",
    "bpSeries": "142/88, 138/86",
    "map": "103 mmHg"
  },
  {
    "id": "P-0005",
    "name": "Omar El‑Sayed",
    "sex": "Male",
    "age": 73,
    "department": "ICU",
    "admissionDate": "2026-02-28",
    "bedNo": "ICU-02",
    "bloodType": "O+",
    "allergiesText": "Aspirin (bronchospasm)",
    "previousSurgeries": "PCI with stent (2022)",
    "admissionWeight": "70 kg",
    "todayWeight": "70.8 kg",
    "height": "170 cm",
    "bmi": "24.5",
    "admissionReason": "Acute shortness of breath, hypotension",
    "medicalDiagnosis": "Acute decompensated heart failure, type 2 respiratory failure",
    "complications": "Required non‑invasive ventilation on admission",
    "conditions": [
      "Chronic heart failure",
      "Ischemic heart disease",
      "Chronic kidney disease stage 3"
    ],
    "medications": [
      "Furosemide 40 mg IV BID",
      "Carvedilol 6.25 mg BID",
      "Spironolactone 25 mg OD"
    ],
    "allergies": [
      "Aspirin"
    ],
    "respType": "Non‑invasive ventilation",
    "respRhythm": "Irregular",
    "respRate": 26,
    "respPattern": "Tachypnea",
    "chestExcursion": "Decreased bilaterally with basal crackles",
    "o2Percent": 40,
    "o2Flow": 8,
    "o2Device": "BiPAP mask",
    "bronchialHygiene": "Assisted coughing, suction PRN",
    "o2Sat": 90,
    "abg": "PaO2 55 mmHg / pH 7.30 / PaCO2 60 mmHg / HCO3 29",
    "incentiveSpirometer": "Not able to use",
    "mdiInhaler": "None",
    "breathSounds": "Fine crackles at both bases",
    "cough": "Weak, productive frothy sputum",
    "chestTube": "None",
    "pulseSeries": [104, 108, 102],
    "pulseRate": 106,
    "pulseRhythm": "Irregular",
    "pulseAmplitude": "+1 weak",
    "heartSounds": "S3 present, no murmur",
    "bpSeries": "98/60, 94/58",
    "map": "72 mmHg"
  }
]
